name: Deploy to Development

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest
    steps:
      - name: Create github deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          mediaType: |
            previews:
              - ant-man
          ref: ${{ github.ref }}
          environment: "Development"
          auto_merge: false
          production_environment: false
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_ORG_PAT }} # using a PAT here as the GITHUB_TOKEN doesn't propagate events (https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow)
