name: Build and Deploy to Staging

on: workflow_dispatch

env:
  PROJECT: a4bird-memories
  NODE_VERSION: 12.16.1
  AWS_PRIMARY_REGION: ap-southeast-2
  AWS_REGION: ap-southeast-2
  AWS_ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/admin


jobs:
  setup:
    name: Setup Variables
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-slug.outputs.branch }}
      slug: ${{ steps.branch-slug.outputs.slug }}
    steps:
      - name: Create Slug
        id: branch-slug
        run: |
          branch_ref=${GITHUB_REF#refs/heads/}
          branch="${GITHUB_HEAD_REF:-$branch_ref}"
          slug="${branch//\//-}"
          echo ::set-output name=branch::${branch}
          echo ::set-output name=slug::${slug,,}
      - name: Display branch slug output
        id: branch-slug-output
        run: |
          echo "branch is ${branch}"
          echo "slug is ${slug}"
        env:
          branch: ${{steps.branch-slug.outputs.branch}}
          slug: ${{steps.branch-slug.outputs.slug}}

  s3bucket:
    name: Setup s3 bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: login-aws
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_PRIMARY_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200

      - name: Create s3bucket if not exists
        run: bash ./s3bucket.sh
        working-directory: ./build-scripts
        env:
          BUCKET_NAME: ${{ env.PROJECT }}
  ci:
    name: Lint, Test and Build
    runs-on: ubuntu-18.04
    needs: [setup, s3bucket]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: login-aws
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_PRIMARY_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
          always-auth: true
          scope: '@a4bird'
          registry-url: https://npm.pkg.github.com

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # - name: Run static checks
      #   run: yarn static-ci

      - name: Run tests
        run: yarn test

      - name: Create build folder
        run: yarn build:staging
        env:
          CI: false

      - name: Run build.sh
        working-directory: ./build-scripts
        run: bash ./build.sh
        env:
          GIT_SHA: ${{ github.sha }}
          VERSION: ${{ format('1.0.0.{0}', github.run_number) }}
          BRANCH: ${{ needs.setup.outputs.branch }}
          SLUG: ${{ needs.setup.outputs.slug }}
          PROJECT: ${{ env.PROJECT }}

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Master
        if: github.ref != 'refs/heads/master'
        run: |
          echo "::error ::Only master deployments can be deployed beyond Development"
          exit 1;

      - name: Create github deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          mediaType: |
            previews:
              - ant-man
          ref: ${{ github.ref }}
          environment: "Staging"
          auto_merge: false
          production_environment: false
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_ORG_PAT }} # using a PAT here as the GITHUB_TOKEN doesn't propagate events (https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow)
